--Insert ROLE
INSERT INTO `ROLE` (`NOM`) VALUES ( 'ROLE_ADMIN');
INSERT INTO `ROLE` ( `NOM`) VALUES ( 'ROLE_USER');

--Insert SALARIE
INSERT INTO `SALARIE` ( `NOM`, `PRENOM`, `USERNAME`, `PASSWORD`, `ID_ROLE`) VALUES ('Badouch', 'mohamed', 'badouch', 'password', '2');
INSERT INTO `SALARIE` ( `NOM`, `PRENOM`, `USERNAME`, `PASSWORD`, `ID_ROLE`) VALUES ('el merrouni', 'marouane', 'marouane', 'password', '2');
INSERT INTO `SALARIE` ( `NOM`, `PRENOM`, `USERNAME`, `PASSWORD`, `ID_ROLE`) VALUES ('saoud', 'amine', 'saoud', 'password', '2');

INSERT INTO `SALARIE` ( `NOM`, `PRENOM`, `USERNAME`, `PASSWORD`, `ID_ROLE`) VALUES ('akouz', 'mohamed', 'admin', 'admin', '1');





--Insert COMPETITION
INSERT INTO `COMPETITION` (`NOM`, `ANNEE`) VALUES ('Coupe D Afrique Des Nations', '2016-12-1');

--Insert POULE

INSERT INTO POULE (NOM, GROUPE,ID_COMPETITION) VALUES ('A', 1,'1');
INSERT INTO POULE (NOM, GROUPE, ID_COMPETITION) VALUES ('B', 1,'1');
INSERT INTO POULE (NOM, GROUPE, ID_COMPETITION) VALUES ('C', 1,'1');
INSERT INTO POULE (NOM, GROUPE, ID_COMPETITION) VALUES ('D', 1,'1');



--Insert PAYS

insert into PAYS (NOM,LOGO)
values('Maroc','');
insert into PAYS (NOM,LOGO)
values('Togo','');
insert into PAYS (NOM,LOGO)
values('RD Congo','');
insert into PAYS (NOM,LOGO)
values('Cote d Ivoire','');
insert into PAYS (NOM,LOGO)
values('Ghana','');
insert into PAYS (NOM,LOGO)
values('Mali','');
insert into PAYS (NOM,LOGO)
values('Egypte','');
insert into PAYS (NOM,LOGO)
values('Ouganda ','');
insert into PAYS (NOM,LOGO)
values('Gabon','');
insert into PAYS (NOM,LOGO)
values('Burkina Faso','');
insert into PAYS (NOM,LOGO)
values('Cameroun','');
insert into PAYS (NOM,LOGO)
values('Guinée Bissau','');
insert into PAYS (NOM,LOGO)
values('Algérie','');
insert into PAYS (NOM,LOGO)
values('Tunisie','');
insert into PAYS (NOM,LOGO)
values('Sénégal','');
insert into PAYS (NOM,LOGO)
values('Zimbabwe','');


--Insert POUL PAYS

INSERT INTO `POULE_PAYS` (`ID_POULE`, `ID_PAYS`) VALUES ('1', '9');
INSERT INTO `POULE_PAYS` (`ID_POULE`, `ID_PAYS`) VALUES ('1', '10');
INSERT INTO `POULE_PAYS` (`ID_POULE`, `ID_PAYS`) VALUES ('1', '11');
INSERT INTO `POULE_PAYS` (`ID_POULE`, `ID_PAYS`) VALUES ('1', '12');

INSERT INTO `POULE_PAYS` (`ID_POULE`, `ID_PAYS`) VALUES ('2', '13');
INSERT INTO `POULE_PAYS` (`ID_POULE`, `ID_PAYS`) VALUES ('2', '14');
INSERT INTO `POULE_PAYS` (`ID_POULE`, `ID_PAYS`) VALUES ('2', '15');
INSERT INTO `POULE_PAYS` (`ID_POULE`, `ID_PAYS`) VALUES ('2', '16');

INSERT INTO `POULE_PAYS` (`ID_POULE`, `ID_PAYS`) VALUES ('3', '1');
INSERT INTO `POULE_PAYS` (`ID_POULE`, `ID_PAYS`) VALUES ('3', '2');
INSERT INTO `POULE_PAYS` (`ID_POULE`, `ID_PAYS`) VALUES ('3', '3');
INSERT INTO `POULE_PAYS` (`ID_POULE`, `ID_PAYS`) VALUES ('3', '4');

INSERT INTO `POULE_PAYS` (`ID_POULE`, `ID_PAYS`) VALUES ('4', '8');
INSERT INTO `POULE_PAYS` (`ID_POULE`, `ID_PAYS`) VALUES ('4', '5');
INSERT INTO `POULE_PAYS` (`ID_POULE`, `ID_PAYS`) VALUES ('4', '6');
INSERT INTO `POULE_PAYS` (`ID_POULE`, `ID_PAYS`) VALUES ('4', '7');



--Insert RENCONTREE


INSERT INTO `RENCONTRE` ( `DATE`, `BUT_1`, `BUT_2`, `ID_PAYS_1`, `ID_PAYS_2`, `ID_POULE`) VALUES ( '2016-12-01 16:00:00', NULL, NULL, '9', '10', '1');
INSERT INTO `RENCONTRE` ( `DATE`, `BUT_1`, `BUT_2`, `ID_PAYS_1`, `ID_PAYS_2`, `ID_POULE`) VALUES ( '2016-12-01 19:00:00', NULL, NULL, '11', '12', '1');

INSERT INTO `RENCONTRE` ( `DATE`, `BUT_1`, `BUT_2`, `ID_PAYS_1`, `ID_PAYS_2`, `ID_POULE`) VALUES ( '2016-12-02 16:00:00', NULL, NULL, '13', '14', '2');
INSERT INTO `RENCONTRE` ( `DATE`, `BUT_1`, `BUT_2`, `ID_PAYS_1`, `ID_PAYS_2`, `ID_POULE`) VALUES ( '2016-12-02 19:00:00', NULL, NULL, '15', '16', '2');

INSERT INTO `RENCONTRE` ( `DATE`, `BUT_1`, `BUT_2`, `ID_PAYS_1`, `ID_PAYS_2`, `ID_POULE`) VALUES ( '2016-12-03 16:00:00', NULL, NULL, '1', '2', '3');
INSERT INTO `RENCONTRE` ( `DATE`, `BUT_1`, `BUT_2`, `ID_PAYS_1`, `ID_PAYS_2`, `ID_POULE`) VALUES ( '2016-12-03 19:00:00', NULL, NULL, '4', '3', '3');

INSERT INTO `RENCONTRE` ( `DATE`, `BUT_1`, `BUT_2`, `ID_PAYS_1`, `ID_PAYS_2`, `ID_POULE`) VALUES ( '2016-12-04 16:00:00', NULL, NULL, '5', '6', '4');
INSERT INTO `RENCONTRE` ( `DATE`, `BUT_1`, `BUT_2`, `ID_PAYS_1`, `ID_PAYS_2`, `ID_POULE`) VALUES ( '2016-12-04 19:00:00', NULL, NULL, '7', '8', '4');


INSERT INTO `RENCONTRE` ( `DATE`, `BUT_1`, `BUT_2`, `ID_PAYS_1`, `ID_PAYS_2`, `ID_POULE`) VALUES ( '2016-12-05 16:00:00', NULL, NULL, '9', '11', '1');
INSERT INTO `RENCONTRE` ( `DATE`, `BUT_1`, `BUT_2`, `ID_PAYS_1`, `ID_PAYS_2`, `ID_POULE`) VALUES ( '2016-12-05 19:00:00', NULL, NULL, '10', '12', '1');

INSERT INTO `RENCONTRE` ( `DATE`, `BUT_1`, `BUT_2`, `ID_PAYS_1`, `ID_PAYS_2`, `ID_POULE`) VALUES ( '2016-12-06 16:00:00', NULL, NULL, '14', '15', '2');
INSERT INTO `RENCONTRE` ( `DATE`, `BUT_1`, `BUT_2`, `ID_PAYS_1`, `ID_PAYS_2`, `ID_POULE`) VALUES ( '2016-12-06 19:00:00', NULL, NULL, '13', '16', '2');

INSERT INTO `RENCONTRE` ( `DATE`, `BUT_1`, `BUT_2`, `ID_PAYS_1`, `ID_PAYS_2`, `ID_POULE`) VALUES ( '2016-12-07 16:00:00', NULL, NULL, '1', '3', '3');
INSERT INTO `RENCONTRE` ( `DATE`, `BUT_1`, `BUT_2`, `ID_PAYS_1`, `ID_PAYS_2`, `ID_POULE`) VALUES ( '2016-12-07 19:00:00', NULL, NULL, '4', '2', '3');

INSERT INTO `RENCONTRE` ( `DATE`, `BUT_1`, `BUT_2`, `ID_PAYS_1`, `ID_PAYS_2`, `ID_POULE`) VALUES ('2016-12-08 16:00:00', NULL, NULL, '5', '8', '4');
INSERT INTO `RENCONTRE` ( `DATE`, `BUT_1`, `BUT_2`, `ID_PAYS_1`, `ID_PAYS_2`, `ID_POULE`) VALUES ( '2016-12-08 19:00:00', NULL, NULL, '6', '7', '4');


INSERT INTO `RENCONTRE` ( `DATE`, `BUT_1`, `BUT_2`, `ID_PAYS_1`, `ID_PAYS_2`, `ID_POULE`) VALUES ( '2016-12-09 16:00:00', NULL, NULL, '9', '12', '1');
INSERT INTO `RENCONTRE` ( `DATE`, `BUT_1`, `BUT_2`, `ID_PAYS_1`, `ID_PAYS_2`, `ID_POULE`) VALUES ( '2016-12-09 19:00:00', NULL, NULL, '11', '10', '1');

INSERT INTO `RENCONTRE` ( `DATE`, `BUT_1`, `BUT_2`, `ID_PAYS_1`, `ID_PAYS_2`, `ID_POULE`) VALUES ( '2016-12-10 16:00:00', NULL, NULL, '14', '16', '2');
INSERT INTO `RENCONTRE` ( `DATE`, `BUT_1`, `BUT_2`, `ID_PAYS_1`, `ID_PAYS_2`, `ID_POULE`) VALUES ( '2016-12-10 19:00:00', NULL, NULL, '13', '15', '2');

INSERT INTO `RENCONTRE` ( `DATE`, `BUT_1`, `BUT_2`, `ID_PAYS_1`, `ID_PAYS_2`, `ID_POULE`) VALUES ( '2016-12-11 16:00:00', NULL, NULL, '1', '4', '3');
INSERT INTO `RENCONTRE` ( `DATE`, `BUT_1`, `BUT_2`, `ID_PAYS_1`, `ID_PAYS_2`, `ID_POULE`) VALUES ('2016-12-11 19:00:00', NULL, NULL, '2', '3', '3');

INSERT INTO `RENCONTRE` ( `DATE`, `BUT_1`, `BUT_2`, `ID_PAYS_1`, `ID_PAYS_2`, `ID_POULE`) VALUES ( '2016-12-12 16:00:00', NULL, NULL, '5', '7', '4');
INSERT INTO `RENCONTRE` ( `DATE`, `BUT_1`, `BUT_2`, `ID_PAYS_1`, `ID_PAYS_2`, `ID_POULE`) VALUES ( '2016-12-12 19:00:00', NULL, NULL, '6', '8', '4');





-- PRONOSTIC

INSERT INTO `PRONOSTIC` (`BUT_1`, `BUT_2`, `NOTE`, `ID_RENCONTRE`, `ID_SALARIE`) VALUES ('1', '0', '0', '1', '2');
INSERT INTO `PRONOSTIC` (`BUT_1`, `BUT_2`, `NOTE`, `ID_RENCONTRE`, `ID_SALARIE`) VALUES ('5', '4', '0', '2', '2');
INSERT INTO `PRONOSTIC` (`BUT_1`, `BUT_2`, `NOTE`, `ID_RENCONTRE`, `ID_SALARIE`) VALUES ('0', '4', '0', '3', '2');
INSERT INTO `PRONOSTIC` (`BUT_1`, `BUT_2`, `NOTE`, `ID_RENCONTRE`, `ID_SALARIE`) VALUES ('4', '6', '0', '4', '2');
INSERT INTO `PRONOSTIC` (`BUT_1`, `BUT_2`, `NOTE`, `ID_RENCONTRE`, `ID_SALARIE`) VALUES ('2', '0', '0', '5', '2');
INSERT INTO `PRONOSTIC` (`BUT_1`, `BUT_2`, `NOTE`, `ID_RENCONTRE`, `ID_SALARIE`) VALUES ('1', '4', '0', '6', '2');


INSERT INTO `PRONOSTIC` (`BUT_1`, `BUT_2`, `NOTE`, `ID_RENCONTRE`, `ID_SALARIE`) VALUES ('0', '0', '0', '1', '3');
INSERT INTO `PRONOSTIC` (`BUT_1`, `BUT_2`, `NOTE`, `ID_RENCONTRE`, `ID_SALARIE`) VALUES ('5', '5', '0', '2', '3');
INSERT INTO `PRONOSTIC` (`BUT_1`, `BUT_2`, `NOTE`, `ID_RENCONTRE`, `ID_SALARIE`) VALUES ('4', '1', '0', '3', '3');
INSERT INTO `PRONOSTIC` (`BUT_1`, `BUT_2`, `NOTE`, `ID_RENCONTRE`, `ID_SALARIE`) VALUES ('0', '5', '0', '4', '3');
INSERT INTO `PRONOSTIC` (`BUT_1`, `BUT_2`, `NOTE`, `ID_RENCONTRE`, `ID_SALARIE`) VALUES ('0', '5', '0', '5', '3');
INSERT INTO `PRONOSTIC` (`BUT_1`, `BUT_2`, `NOTE`, `ID_RENCONTRE`, `ID_SALARIE`) VALUES ('3', '0', '0', '6', '3');


INSERT INTO `PRONOSTIC` (`BUT_1`, `BUT_2`, `NOTE`, `ID_RENCONTRE`, `ID_SALARIE`) VALUES ('4', '2', '0', '1', '1');
INSERT INTO `PRONOSTIC` (`BUT_1`, `BUT_2`, `NOTE`, `ID_RENCONTRE`, `ID_SALARIE`) VALUES ('6', '2', '0', '2', '1');
INSERT INTO `PRONOSTIC` (`BUT_1`, `BUT_2`, `NOTE`, `ID_RENCONTRE`, `ID_SALARIE`) VALUES ('6', '0', '0', '3', '1');
INSERT INTO `PRONOSTIC` (`BUT_1`, `BUT_2`, `NOTE`, `ID_RENCONTRE`, `ID_SALARIE`) VALUES ('1', '0', '0', '4', '1');
INSERT INTO `PRONOSTIC` (`BUT_1`, `BUT_2`, `NOTE`, `ID_RENCONTRE`, `ID_SALARIE`) VALUES ('5', '2', '0', '5', '1');
INSERT INTO `PRONOSTIC` (`BUT_1`, `BUT_2`, `NOTE`, `ID_RENCONTRE`, `ID_SALARIE`) VALUES ('5', '0', '0', '6', '1');
INSERT INTO `PRONOSTIC` (`BUT_1`, `BUT_2`, `NOTE`, `ID_RENCONTRE`, `ID_SALARIE`) VALUES ('6', '5', '0', '7', '1');


