CREATE TABLE IF NOT EXISTS `COMPETITION` (
  `ID_COMPETITION` INT NOT NULL AUTO_INCREMENT,
  `NOM` VARCHAR(45) NULL,
  `ANNEE` TIMESTAMP NULL,
  PRIMARY KEY (`ID_COMPETITION`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `POULE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `POULE` (
  `ID_POULE` INT NOT NULL AUTO_INCREMENT,
  `NOM` VARCHAR(45) NULL,
  `GROUPE` BOOLEAN ,
  `ID_COMPETITION` INT NOT NULL,
  PRIMARY KEY (`ID_POULE`),
  CONSTRAINT `fk_POULE_COMPETITION1`
  FOREIGN KEY (`ID_COMPETITION`)
  REFERENCES `COMPETITION` (`ID_COMPETITION`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PAYS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PAYS` (
  `ID_PAYS` INT NOT NULL AUTO_INCREMENT,
  `NOM` VARCHAR(45) NULL,
  `LOGO` VARCHAR(128) NULL,
  PRIMARY KEY (`ID_PAYS`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `RENCONTRE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `RENCONTRE` (
  `ID_RENCONTRE` INT NOT NULL AUTO_INCREMENT,
  `DATE` TIMESTAMP NULL,
  `BUT_1` INT NULL,
  `BUT_2` INT NULL,
  `ID_PAYS_1` INT NOT NULL,
  `ID_PAYS_2` INT NOT NULL,
  `ID_POULE` INT NULL,
  PRIMARY KEY (`ID_RENCONTRE`),

  CONSTRAINT `fk_RENCONTRE_PAYS1`
  FOREIGN KEY (`ID_PAYS_1`)
  REFERENCES `PAYS` (`ID_PAYS`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION,
  CONSTRAINT `fk_RENCONTRE_PAYS2`
  FOREIGN KEY (`ID_PAYS_2`)
  REFERENCES `PAYS` (`ID_PAYS`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION,
  CONSTRAINT `fk_RENCONTRE_POULE1`
  FOREIGN KEY (`ID_POULE`)
  REFERENCES `POULE` (`ID_POULE`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ROLE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ROLE` (
  `ID_ROLE` INT NOT NULL AUTO_INCREMENT,
  `NOM` VARCHAR(45) NULL,
  PRIMARY KEY (`ID_ROLE`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SALARIE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SALARIE` (
  `ID_SALARIE` INT NOT NULL AUTO_INCREMENT,
  `NOM` VARCHAR(45) NULL,
  `PRENOM` VARCHAR(45) NULL,
  `USERNAME` VARCHAR(45) NULL,
  `PASSWORD` VARCHAR(45) NULL,
  `ID_ROLE` INT NOT NULL,
  PRIMARY KEY (`ID_SALARIE`),

  CONSTRAINT `fk_SALARIE_ROLE1`
  FOREIGN KEY (`ID_ROLE`)
  REFERENCES `ROLE` (`ID_ROLE`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PRONOSTIC`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PRONOSTIC` (
  `ID_PRONOSTIC` INT NOT NULL AUTO_INCREMENT,
  `BUT_1` INT NULL,
  `BUT_2` INT NULL,
  `NOTE` INT DEFAULT 0,
  `ID_RENCONTRE` INT NOT NULL,
  `ID_SALARIE` INT NOT NULL,

  PRIMARY KEY (`ID_PRONOSTIC`),

  CONSTRAINT `fk_PRONOSTIC_RENCONTRE1`
  FOREIGN KEY (`ID_RENCONTRE`)
  REFERENCES `RENCONTRE` (`ID_RENCONTRE`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION,
  CONSTRAINT `fk_PRONOSTIC_SALARIE1`
  FOREIGN KEY (`ID_SALARIE`)
  REFERENCES `SALARIE` (`ID_SALARIE`)
  ON DELETE CASCADE
  ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `POULE_PAYS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `POULE_PAYS` (
  `ID_POULE` INT NOT NULL,
  `ID_PAYS` INT NOT NULL,
  PRIMARY KEY (`ID_POULE`, `ID_PAYS`),

  CONSTRAINT `fk_POULE_has_PAYS_POULE`
  FOREIGN KEY (`ID_POULE`)
  REFERENCES `POULE` (`ID_POULE`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION,
  CONSTRAINT `fk_POULE_has_PAYS_PAYS1`
  FOREIGN KEY (`ID_PAYS`)
  REFERENCES `PAYS` (`ID_PAYS`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION)
ENGINE = InnoDB;
